export enum ExpEnum {
    Woodcutting = 'Woodcutting',
    Woodworking = 'Woodworking',
    Mining = 'Mining',
    Smithing = 'Smithing',
    Archery = 'Archery',
    OneHanded = 'OneHanded',
    TwoHanded = 'TwoHanded ',
    Block = 'Block',
    LightArmour = 'LightArmour',
    MediumArmour = 'MediumArmour',
    HeavyArmour = 'HeavyArmour',
    Butchering = 'Butchering',
    Alchemy = 'Alchemy',
    Gathering = 'Gathering',
    Persuasion = 'Persuasion',
}
