export enum CollapsedEnum {
    Gathering = 'Gathering',
    Combat = 'Combat',
    Characters = 'Characters',
    Mining = 'Mining',
    Woodcutting = 'Woodcutting',
    World = 'World',
    Sidebar = 'Sidebar',
    BattleArea = 'BattleArea',
    GatheringSide = 'GatheringSide',
    CraftingSide = 'CraftingSide',
    Perk = 'Perk',
    PerkS = 'PerkS',
    AbilityList = 'AbilityList',
    CombatSide = 'CombatSide',
    Forest = 'Forest',
    Quest = 'Quest',
    QuestAccepted = 'QuestAccepted',
    QuestAvailable = 'QuestAvailable',
}
