import { FAST_MINING_PERK } from '../mining/MiningCost'
import { FAST_WOODCUTTING_PERK } from '../wood/WoodConst'
import { Msg, MsgFunctions } from './Msg'

export const engMsg: Msg = {
    Activities: 'Activities',
    Storage: 'Storage',
    Woodcutting: 'Woodcutting',
    Woodworking: 'Woodworking',
    Time: 'Time',
    Stop: 'Stop',
    CraftingUnknown: 'Crafting ??',
    DeadTree: 'Dead Tree',
    Oak: 'Oak',
    DeadTreeLog: 'Dead Tree Log',
    OakLog: 'Oak Log',
    DeadTreePlank: 'Dead Tree Plank',
    OakPlank: 'Oak Plank',
    DeadTreeForest: 'Dead Tree Forest',
    OakForest: 'Oak Forest',
    Cutting: 'Cutting',
    TreeHP: 'Tree HP',
    Cut: 'Cut',
    Trees: 'Trees',
    GrowingTrees: 'Growing Trees',
    MoveUp: 'Move Up',
    MoveDown: 'Move Down',
    Remove: 'Remove',
    Log: 'Log',
    None: 'None',
    Recipe: 'Recipe',
    Plank: 'Plank',
    Requirements: 'Requirements',
    NoItems: "You don't possess anything!",
    NoActivities: "There aren't any activity",
    Craft: 'Craft',
    Sort: 'Sort',
    Name: 'Name',
    Quantity: 'Quantity',
    Value: 'Value',
    Handle: 'Handle',
    DeadTreeHandle: 'Dead Tree Handle',
    OakHandle: 'Oak Handle',
    CopperOre: 'Copper Ore',
    TinOre: 'Tin Ore',
    Mining: 'Mining',
    OreHp: 'Ore Hp',
    Mine: 'Mine',
    OreQta: 'Quantity',
    OreVein: 'Ore Vein',
    Level: 'Level',
    XP: 'XP',
    MiningExp: 'Mining Level',
    WoodcuttingExp: 'Woodcutting Level',
    WoodworkingExp: 'Woodworking Level',
    SmithingExp: 'Smithing Level',
    Ore: 'Ore',
    Bar: 'Bar',
    TinBar: 'Tin Bar',
    CopperBar: 'Copper Bar',
    Smithing: 'Smithing',
    WoodAxe: 'Wood Axe',
    Crafting: 'Crafting',
    Gathering: 'Gathering',
    ItemType: 'Type',
    Damage: 'Damage',
    AttackSpeed: 'Attack Speed',
    Pickaxe: 'Pickaxe',
    ArmourPen: 'Armour Pen.',
    WoodcuttingDamage: 'Woodcutting Damage',
    WoodcuttingTime: 'Woodcutting  Time',
    // Perks
    Perks: 'Perks',
    Available: 'Available',
    NotAvailable: 'Not Available',
    Completed: 'Owned',
    Select: 'Select',
    Base: 'Base',
    Total: 'Total',
    Used: 'Used',
    Filter: 'Filter',
    Attributes: 'Attributes',
    healthPoints: 'Health Points',
    StaminaPoints: 'Stamina Points',
    ManaPoints: 'Mana Points',
    Health: 'Health',
    Stamina: 'Stamina',
    Mana: 'Mana',

    FastWoodcuttingPerk: 'Fast Woodcutting',
    FastWoodcuttingPerkDesc: `Increase woodcutting speed by ${FAST_WOODCUTTING_PERK} %`,
    FastMiningPerk: 'Fast Mining',
    FastMiningPerkDesc: `Increase mining speed by ${FAST_MINING_PERK} %`,

    ActivityAdded: 'Activity added',
    NormalAttack: 'Normal Attack',
    NormalAttackDesc: 'Normal Attack',

    CombatZones: 'Combat',

    // battle
    Forest: 'Forest',
    Boar: 'Boar',
    Wolves: 'Wolves',
}
export const makeEngMsg: (msg: Msg) => MsgFunctions = (msg: Msg) => ({
    years: (qta: number, formattedQta: string) => `${formattedQta} ${qta === 1 ? 'year' : 'years'}`,
    months: (qta: number, formattedQta: string) => `${formattedQta} ${qta === 1 ? 'month' : 'months'}`,
    days: (qta: number, formattedQta: string) => `${formattedQta} ${qta === 1 ? 'day' : 'days'}`,
    h: (_qta: number, formattedQta: string) => `${formattedQta}h`,
    m: (_qta: number, formattedQta: string) => `${formattedQta}m`,
    s: (_qta: number, formattedQta: string) => `${formattedQta}s`,
    cutting: (woodName: keyof Msg) => `Cutting ${msg[woodName]}`,
    crafting: (itemNameId: keyof Msg) => `Crafting ${msg[itemNameId]}`,
    mining: (oreNameId: keyof Msg) => `Mining ${msg[oreNameId]}`,
    speedBonusPercent: (bonus: string) => `Speed bonus +${bonus}%`,
    prestigePercent: (bonus: string) => `Value bonus +${bonus}%`,
    fighting: (enemy: keyof Msg) => `Fighting ${msg[enemy]}`,
})
