import { Msg, MsgFunctions } from './Msg'

export const engMsg: Msg = {
    Activities: 'Activities',
    Storage: 'Storage',
    Woodcutting: 'Woodcutting',
    Woodworking: 'Woodworking',
    Time: 'Time',
    Stop: 'Stop',
    CraftingUnknown: 'Crafting ??',
    DeadTree: 'Dead Tree',
    Oak: 'Oak',
    DeadTreeLog: 'Dead Tree Log',
    OakLog: 'Oak Log',
    DeadTreePlank: 'Dead Tree Plank',
    OakPlank: 'Oak Plank',
    DeadTreeForest: 'Dead Tree Forest',
    OakForest: 'Oak Forest',
    Cutting: 'Cutting',
    TreeHP: 'Tree HP',
    Cut: 'Cut',
    Trees: 'Trees',
    GrowingTrees: 'Growing Trees',
    MoveUp: 'Move Up',
    MoveDown: 'Move Down',
    Remove: 'Remove',
    Log: 'Log',
    None: 'None',
    Recipe: 'Recipe',
    Plank: 'Plank',
    Requirements: 'Requirements',
    NoItems: "You don't possess anything!",
    NoActivities: "There aren't any activity",
    Craft: 'Craft',
    Sort: 'Sort',
    Name: 'Name',
    Quantity: 'Quantity',
    Value: 'Value',
    Handle: 'Handle',
    DeadTreeHandle: 'Dead Tree Handle',
    OakHandle: 'Oak Handle',
    CopperOre: 'Copper Ore',
    TinOre: 'Tin Ore',
    Mining: 'Mining',
    OreHp: 'Ore Hp',
    Mine: 'Mine',
    OreQta: 'Quantity',
    OreVein: 'Ore Vein',
    Level: 'Level',
    XP: 'XP',
    MiningExp: 'Mining Level',
    WoodcuttingExp: 'Woodcutting Level',
    WoodworkingExp: 'Woodworking Level',
    SmithingExp: 'Smithing Level',
    Ore: 'Ore',
    Bar: 'Bar',
    TinBar: 'Tin Bar',
    CopperBar: 'Copper Bar',
    Smithing: 'Smithing',
    WoodAxe: 'Wood Axe',
}
export const makeEngMsg: (msg: Msg) => MsgFunctions = (msg: Msg) => ({
    years: (qta: number, formattedQta: string) => `${formattedQta} ${qta === 1 ? 'year' : 'years'}`,
    months: (qta: number, formattedQta: string) => `${formattedQta} ${qta === 1 ? 'month' : 'months'}`,
    days: (qta: number, formattedQta: string) => `${formattedQta} ${qta === 1 ? 'day' : 'days'}`,
    h: (_qta: number, formattedQta: string) => `${formattedQta}h`,
    m: (_qta: number, formattedQta: string) => `${formattedQta}m`,
    s: (_qta: number, formattedQta: string) => `${formattedQta}s`,
    cutting: (woodName: keyof Msg) => `Cutting ${msg[woodName]}`,
    crafting: (itemNameId: keyof Msg) => `Crafting ${msg[itemNameId]}`,
    mining: (oreNameId: keyof Msg) => `Mining ${msg[oreNameId]}`,
})
