import { Msg, MsgFunctions } from './Msg'

export const engMsg: Msg = {
    Activities: 'Activities',
    Storage: 'Storage',
    Woodcutting: 'Woodcutting',
    Woodworking: 'Woodworking',
    Time: 'Time',
    Stop: 'Stop',
    CraftingUnknown: 'Crafting ??',
    DeadTree: 'Dead Tree',
    Oak: 'Oak',
    DeadTreeLog: 'Dead Tree Log',
    OakLog: 'Oak Log',
    DeadTreePlank: 'Dead Tree Plank',
    OakPlank: 'Oak Plank',
    DeadTreeForest: 'Dead Tree Forest',
    OakForest: 'Oak Forest',
    Cutting: 'Cutting',
    TreeHP: 'Tree HP',
    Cut: 'Cut',
    Trees: 'Trees',
    GrowingTrees: 'Growing Trees',
    MoveUp: 'Move Up',
    MoveDown: 'Move Down',
    Remove: 'Remove',
    Log: 'Log',
    None: 'None',
    Recipe: 'Recipe',
    Plank: 'Plank',
    Requirements: 'Requirements',
    NoItems: "You don't possess anything!",
    NoActivities: "There aren't any activity",
    Craft: 'Craft',
    Sort: 'Sort',
    Name: 'Name',
    Quantity: 'Quantity',
    Value: 'Value',
}
export const makeEngMsg: (msg: Msg) => MsgFunctions = (msg: Msg) => ({
    years: (qta: number, formattedQta: string) => `${formattedQta} ${qta === 1 ? 'year' : 'years'}`,
    months: (qta: number, formattedQta: string) => `${formattedQta} ${qta === 1 ? 'month' : 'months'}`,
    days: (qta: number, formattedQta: string) => `${formattedQta} ${qta === 1 ? 'day' : 'days'}`,
    h: (_qta: number, formattedQta: string) => `${formattedQta}h`,
    m: (_qta: number, formattedQta: string) => `${formattedQta}m`,
    s: (_qta: number, formattedQta: string) => `${formattedQta}s`,
    cutting: (woodName: keyof Msg) => `Cutting ${msg[woodName]}`,
    crafting: (itemNameId: keyof Msg) => `Crafting ${msg[itemNameId]}`,
})
