import { ReactNode } from 'react'
import {
    GiWoodAxe,
    GiLog,
    GiPlanks,
    GiBo,
    GiOre,
    GiMetalBar,
    GiHearts,
    GiHeartPlus,
    GiStrong,
    GiMagicPalm,
    GiBoar,
    GiForest,
    GiWolfHead,
    GiDeadWood,
    GiOak,
    GiPunch,
    GiMining,
    GiSaberSlash,
    GiPiercingSword,
    GiBreastplate,
    GiPlainDagger,
    GiBroadsword,
    GiMeatCleaver,
    GiSteak,
    GiAnimalHide,
    GiShield,
    GiCrossedSwords,
    GiDeathSkull,
} from 'react-icons/gi'

export enum Icons {
    Axe = 'Axe',
    Log = 'Log',
    Plank = 'Plank',
    Handle = 'Handle',
    Ore = 'Ore',
    Bar = 'Bar',
    Pickaxe = 'Pickaxe',
    Heart = 'Heart',
    HeartPlus = 'HeartPlus',
    Strong = 'Strong',
    MagicPalm = 'MagicPalm',
    Boar = 'Boar',
    Forest = 'Forest',
    WolfHead = 'WolfHead',
    DeadWood = 'DeadWood',
    Oak = 'Oak',
    Pine = 'Pine',
    Birch = 'Birch',
    Maple = 'Maple',
    Willow = 'Willow',
    Cedar = 'Cedar',
    Redwood = 'Redwood',
    Spruce = 'Spruce',
    Mahogany = 'Mahogany',
    Punch = 'Punch',
    SaberSlash = 'SaberSlash',
    Sword = 'Sword',
    Breastplate = 'Breastplate',
    Dagger = 'Dagger',
    Broadsword = 'Broadsword',
    MeatCleaver = 'MeatCleaver',
    Steak = 'Steak',
    AnimalHide = 'AnimalHide',
    Shield = 'Shield',
    CrossedSwords = 'CrossedSwords',
    Skull = 'Skull',
}
export const IconsData: Record<Icons, ReactNode> = {
    Axe: <GiWoodAxe />,
    Log: <GiLog />,
    Plank: <GiPlanks />,
    Handle: <GiBo />,
    Ore: <GiOre />,
    Bar: <GiMetalBar />,
    Pickaxe: <GiMining />,
    Heart: <GiHearts />,
    HeartPlus: <GiHeartPlus />,
    Strong: <GiStrong />,
    MagicPalm: <GiMagicPalm />,
    Boar: <GiBoar />,
    Forest: <GiForest />,
    WolfHead: <GiWolfHead />,
    DeadWood: <GiDeadWood />,
    Oak: <GiOak />,
    Pine: <GiLog />,
    Birch: <GiLog />,
    Maple: <GiLog />,
    Willow: <GiLog />,
    Cedar: <GiLog />,
    Redwood: <GiLog />,
    Spruce: <GiLog />,
    Mahogany: <GiLog />,
    Punch: <GiPunch />,
    SaberSlash: <GiSaberSlash />,
    Sword: <GiPiercingSword />,
    Breastplate: <GiBreastplate />,
    Dagger: <GiPlainDagger />,
    Broadsword: <GiBroadsword />,
    MeatCleaver: <GiMeatCleaver />,
    Steak: <GiSteak />,
    AnimalHide: <GiAnimalHide />,
    Shield: <GiShield />,
    CrossedSwords: <GiCrossedSwords />,
    Skull: <GiDeathSkull />,
}
