import { ReactNode } from 'react'
import {
    GiWoodAxe,
    GiLog,
    GiPlanks,
    GiBo,
    GiOre,
    GiMetalBar,
    GiHearts,
    GiHeartPlus,
    GiStrong,
    GiMagicPalm,
    GiBoar,
    GiForest,
    GiWolfHead,
    GiDeadWood,
    GiOak,
    GiPunch,
    GiMining,
    GiSaberSlash,
    GiPiercingSword,
    GiBreastplate,
    GiPlainDagger,
    GiBroadsword,
    GiMeatCleaver,
    GiSteak,
} from 'react-icons/gi'

export enum Icons {
    Axe = 'Axe',
    Log = 'Log',
    Plank = 'Plank',
    Handle = 'Handle',
    Ore = 'Ore',
    Bar = 'Bar',
    Pickaxe = 'Pickaxe',
    Heart = 'Heart',
    HeartPlus = 'HeartPlus',
    Strong = 'Strong',
    MagicPalm = 'MagicPalm',
    Boar = 'Boar',
    Forest = 'Forest',
    WolfHead = 'WolfHead',
    DeadWood = 'DeadWood',
    Oak = 'Oak',
    Punch = 'Punch',
    SaberSlash = 'SaberSlash',
    Sword = 'Sword',
    Breastplate = 'Breastplate',
    Dagger = 'Dagger',
    Broadsword = 'Broadsword',
    MeatCleaver = 'MeatCleaver',
    Steak = 'Steak',
}
export const IconsData: { [k in Icons]: ReactNode } = {
    Axe: <GiWoodAxe />,
    Log: <GiLog />,
    Plank: <GiPlanks />,
    Handle: <GiBo />,
    Ore: <GiOre />,
    Bar: <GiMetalBar />,
    Pickaxe: <GiMining />,
    Heart: <GiHearts />,
    HeartPlus: <GiHeartPlus />,
    Strong: <GiStrong />,
    MagicPalm: <GiMagicPalm />,
    Boar: <GiBoar />,
    Forest: <GiForest />,
    WolfHead: <GiWolfHead />,
    DeadWood: <GiDeadWood />,
    Oak: <GiOak />,
    Punch: <GiPunch />,
    SaberSlash: <GiSaberSlash />,
    Sword: <GiPiercingSword />,
    Breastplate: <GiBreastplate />,
    Dagger: <GiPlainDagger />,
    Broadsword: <GiBroadsword />,
    MeatCleaver: <GiMeatCleaver />,
    Steak: <GiSteak />,
}
