import { ReactNode } from 'react'
import {
    GiAnimalHide,
    GiArmoredPants,
    GiBo,
    GiBoar,
    GiBoots,
    GiBreastplate,
    GiBroadsword,
    GiChicken,
    GiConversation,
    GiCrossedSwords,
    GiDeadWood,
    GiDeathSkull,
    GiDroplets,
    GiFizzingFlask,
    GiForest,
    GiGauntlet,
    GiHeartPlus,
    GiHearts,
    GiHorseHead,
    GiLindenLeaf,
    GiLog,
    GiMagicPalm,
    GiMeatCleaver,
    GiMetalBar,
    GiMining,
    GiOak,
    GiOldWagon,
    GiOre,
    GiPiercingSword,
    GiPlainDagger,
    GiPlanks,
    GiPunch,
    GiRoundBottomFlask,
    GiRupee,
    GiSaberSlash,
    GiShield,
    GiSpottedMushroom,
    GiSteak,
    GiStrong,
    GiSwapBag,
    GiTreeGrowth,
    GiTwoCoins,
    GiVanillaFlower,
    GiWolfHead,
    GiWoodAxe,
    GiVisoredHelm,
    GiHutsVillage,
    GiReceiveMoney,
} from 'react-icons/gi'
import { LuArrowDown, LuArrowDownUp, LuArrowUp } from 'react-icons/lu'

export enum Icons {
    Axe = 'Axe',
    Log = 'Log',
    Plank = 'Plank',
    Handle = 'Handle',
    Ore = 'Ore',
    Bar = 'Bar',
    Pickaxe = 'Pickaxe',
    Heart = 'Heart',
    HeartPlus = 'HeartPlus',
    Strong = 'Strong',
    MagicPalm = 'MagicPalm',
    Boar = 'Boar',
    Forest = 'Forest',
    WolfHead = 'WolfHead',
    DeadWood = 'DeadWood',
    Oak = 'Oak',
    Punch = 'Punch',
    SaberSlash = 'SaberSlash',
    Sword = 'Sword',
    Breastplate = 'Breastplate',
    Dagger = 'Dagger',
    Broadsword = 'Broadsword',
    MeatCleaver = 'MeatCleaver',
    Steak = 'Steak',
    AnimalHide = 'AnimalHide',
    Shield = 'Shield',
    CrossedSwords = 'CrossedSwords',
    Skull = 'Skull',
    Coins = 'Coins',
    Potion = 'Potion',
    OppositeIngredient = 'OppositeIngredient',
    MultipleEffects = 'MultipleEffects',
    ArrowUp = 'ArrowUp',
    ArrowDown = 'ArrowDown',
    RoundPotion = 'RoundPotion',
    VanillaFlower = 'VanillaFlower',
    Chicken = 'Chicken',
    Leaf = 'Leaf',
    Mushroom = 'Mushroom',
    SwapBag = 'SwapBag',
    Rupee = 'Rupee',
    Cuisses = 'Cuisses',
    Helmet = 'Helmet',
    Gauntlet = 'Gauntlet',
    Boots = 'Boots',
    HutsVillage = 'HutsVillage',
    Tree = 'Tree',
    HeavyCart = 'HeavyCart',
    FastCourier = 'FastCourier',
    Market = 'Market',
    Persuasion = 'Persuasion',
}
export const IconsData: Record<Icons, ReactNode> = {
    Axe: <GiWoodAxe />,
    Log: <GiLog />,
    Plank: <GiPlanks />,
    Handle: <GiBo />,
    Ore: <GiOre />,
    Bar: <GiMetalBar />,
    Pickaxe: <GiMining />,
    Heart: <GiHearts />,
    HeartPlus: <GiHeartPlus />,
    Strong: <GiStrong />,
    MagicPalm: <GiMagicPalm />,
    Boar: <GiBoar />,
    Forest: <GiForest />,
    WolfHead: <GiWolfHead />,
    DeadWood: <GiDeadWood />,
    Oak: <GiOak />,
    Punch: <GiPunch />,
    SaberSlash: <GiSaberSlash />,
    Sword: <GiPiercingSword />,
    Breastplate: <GiBreastplate />,
    Dagger: <GiPlainDagger />,
    Broadsword: <GiBroadsword />,
    MeatCleaver: <GiMeatCleaver />,
    Steak: <GiSteak />,
    AnimalHide: <GiAnimalHide />,
    Shield: <GiShield />,
    CrossedSwords: <GiCrossedSwords />,
    Skull: <GiDeathSkull />,
    Coins: <GiTwoCoins />,
    Potion: <GiFizzingFlask />,
    OppositeIngredient: <LuArrowDownUp />,
    MultipleEffects: <GiDroplets />,
    ArrowUp: <LuArrowUp />,
    ArrowDown: <LuArrowDown />,
    RoundPotion: <GiRoundBottomFlask />,
    VanillaFlower: <GiVanillaFlower />,
    Chicken: <GiChicken />,
    Leaf: <GiLindenLeaf />,
    Mushroom: <GiSpottedMushroom />,
    SwapBag: <GiSwapBag />,
    Rupee: <GiRupee />,
    Cuisses: <GiArmoredPants />,
    Helmet: <GiVisoredHelm />,
    Gauntlet: <GiGauntlet />,
    Boots: <GiBoots />,
    HutsVillage: <GiHutsVillage />,
    Tree: <GiTreeGrowth />,
    HeavyCart: <GiOldWagon />,
    FastCourier: <GiHorseHead />,
    Market: <GiReceiveMoney />,
    Persuasion: <GiConversation />,
}
