import { Item, ItemTypes } from '../items/Item'
import { Icons } from '../icons/Icons'

export const WoodItems = {
    DeadTreeLog: {
        id: 'DeadTreeLog',
        icon: Icons.Log,
        nameId: 'DeadTreeLog',
        type: ItemTypes.Log,
        value: 5,
    },
    OakLog: {
        id: 'OakLog',
        icon: Icons.Log,
        nameId: 'OakLog',
        type: ItemTypes.Log,
        value: 6,
    },

    // plank
    DeadTreePlank: {
        id: 'DeadTreePlank',
        icon: Icons.Plank,
        nameId: 'DeadTreePlank',
        type: ItemTypes.Plank,
        value: 10,
    },
    OakPlank: {
        id: 'OakPlank',
        icon: Icons.Plank,
        nameId: 'OakPlank',
        type: ItemTypes.Plank,
        value: 12,
    },
    PineLog: {
        id: 'PineLog',
        icon: Icons.Log,
        nameId: 'PineLog',
        type: ItemTypes.Log,
        value: 7,
    },
    PinePlank: {
        id: 'PinePlank',
        icon: Icons.Plank,
        nameId: 'PinePlank',
        type: ItemTypes.Plank,
        value: 14,
    },
    PineHandle: {
        id: 'PineHandle',
        icon: Icons.Handle,
        nameId: 'PineHandle',
        type: ItemTypes.Handle,
        value: 22,
        craftingData: { prestige: 1, speedBonus: 1.2 },
    },
    BirchLog: {
        id: 'BirchLog',
        icon: Icons.Log,
        nameId: 'BirchLog',
        type: ItemTypes.Log,
        value: 8,
    },
    BirchPlank: {
        id: 'BirchPlank',
        icon: Icons.Plank,
        nameId: 'BirchPlank',
        type: ItemTypes.Plank,
        value: 16,
    },
    BirchHandle: {
        id: 'BirchHandle',
        icon: Icons.Handle,
        nameId: 'BirchHandle',
        type: ItemTypes.Handle,
        value: 24,
        craftingData: { prestige: 1, speedBonus: 1.3 },
    },
    MapleLog: {
        id: 'MapleLog',
        icon: Icons.Log,
        nameId: 'MapleLog',
        type: ItemTypes.Log,
        value: 9,
    },
    MaplePlank: {
        id: 'MaplePlank',
        icon: Icons.Plank,
        nameId: 'MaplePlank',
        type: ItemTypes.Plank,
        value: 18,
    },
    MapleHandle: {
        id: 'MapleHandle',
        icon: Icons.Handle,
        nameId: 'MapleHandle',
        type: ItemTypes.Handle,
        value: 26,
        craftingData: { prestige: 1, speedBonus: 1.4 },
    },
    WillowLog: {
        id: 'WillowLog',
        icon: Icons.Log,
        nameId: 'WillowLog',
        type: ItemTypes.Log,
        value: 10,
    },
    WillowPlank: {
        id: 'WillowPlank',
        icon: Icons.Plank,
        nameId: 'WillowPlank',
        type: ItemTypes.Plank,
        value: 20,
    },
    WillowHandle: {
        id: 'WillowHandle',
        icon: Icons.Handle,
        nameId: 'WillowHandle',
        type: ItemTypes.Handle,
        value: 28,
        craftingData: { prestige: 1, speedBonus: 1.5 },
    },
    CedarLog: {
        id: 'CedarLog',
        icon: Icons.Log,
        nameId: 'CedarLog',
        type: ItemTypes.Log,
        value: 11,
    },
    CedarPlank: {
        id: 'CedarPlank',
        icon: Icons.Plank,
        nameId: 'CedarPlank',
        type: ItemTypes.Plank,
        value: 22,
    },
    CedarHandle: {
        id: 'CedarHandle',
        icon: Icons.Handle,
        nameId: 'CedarHandle',
        type: ItemTypes.Handle,
        value: 30,
        craftingData: { prestige: 1, speedBonus: 1.6 },
    },
    RedwoodLog: {
        id: 'RedwoodLog',
        icon: Icons.Log,
        nameId: 'RedwoodLog',
        type: ItemTypes.Log,
        value: 12,
    },
    RedwoodPlank: {
        id: 'RedwoodPlank',
        icon: Icons.Plank,
        nameId: 'RedwoodPlank',
        type: ItemTypes.Plank,
        value: 24,
    },
    RedwoodHandle: {
        id: 'RedwoodHandle',
        icon: Icons.Handle,
        nameId: 'RedwoodHandle',
        type: ItemTypes.Handle,
        value: 32,
        craftingData: { prestige: 1, speedBonus: 1.7 },
    },
    SpruceLog: {
        id: 'SpruceLog',
        icon: Icons.Log,
        nameId: 'SpruceLog',
        type: ItemTypes.Log,
        value: 13,
    },
    SprucePlank: {
        id: 'SprucePlank',
        icon: Icons.Plank,
        nameId: 'SprucePlank',
        type: ItemTypes.Plank,
        value: 26,
    },
    SpruceHandle: {
        id: 'SpruceHandle',
        icon: Icons.Handle,
        nameId: 'SpruceHandle',
        type: ItemTypes.Handle,
        value: 34,
        craftingData: { prestige: 1, speedBonus: 1.8 },
    },
    MahoganyLog: {
        id: 'MahoganyLog',
        icon: Icons.Log,
        nameId: 'MahoganyLog',
        type: ItemTypes.Log,
        value: 14,
    },
    MahoganyPlank: {
        id: 'MahoganyPlank',
        icon: Icons.Plank,
        nameId: 'MahoganyPlank',
        type: ItemTypes.Plank,
        value: 28,
    },
    MahoganyHandle: {
        id: 'MahoganyHandle',
        icon: Icons.Handle,
        nameId: 'MahoganyHandle',
        type: ItemTypes.Handle,
        value: 36,
        craftingData: { prestige: 1, speedBonus: 1.9 },
    },
} satisfies Record<string, Item>
