export const MAX_INGREDIENTS = 4
export const NEGATIVE_EFFECT_STABILITY_PENALTY = -0.2
export const STABILITY_UNSTABLE = 30
export const STABILITY_STABLE = 70
export const UNSTABLE_POTENCY_PERCENT = 0.25
export const CHAOTIC_POTENCY_PERCENT = 0.5
export const MULTIPLE_EFFECTS_STABILITY = -5
